// Auto-generated by scripts/build-protocol-data.mjs
// Do not edit this file directly.

const PROTOCOL_DATA = {
  "PET": {
    "title": "FDG PET / CT 腫瘤影像",
    "source": "EANM / SNMMI guideline for FDG PET / CT: tumour imaging",
    "acquisition": [
      [
        "Detector / modality",
        "PET / CT"
      ],
      [
        "Tracer",
        "18F-FDG"
      ],
      [
        "Patient prep",
        "禁食 4–6 小時；避免劇烈運動；控制血糖；等待期維持安靜與保暖"
      ],
      [
        "Uptake time",
        "常規約 60 分鐘；科內應固定容許範圍"
      ],
      [
        "Position",
        "supine，arms up / down 依 protocol 固定"
      ],
      [
        "FOV / scan range",
        "skull base 至 mid-thigh；依病情可延至 vertex 或下肢"
      ],
      [
        "Time / bed",
        "數位 PET 多約 1.5–3 分鐘 / bed；較舊系統常約 2–4 分鐘 / bed"
      ],
      [
        "CT role",
        "低劑量 CT AC / localization 為基本；必要時診斷 CT"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "OSEM，現代系統多合併 TOF"
      ],
      [
        "Iterations / subsets",
        "依 vendor validated preset 固定"
      ],
      [
        "Attenuation correction",
        "CT AC"
      ],
      [
        "Scatter correction",
        "vendor preset"
      ],
      [
        "Resolution recovery / PSF",
        "視系統可用"
      ],
      [
        "Motion correction",
        "視需要；但明顯 motion 應優先辨識而非硬修"
      ],
      [
        "Quantification",
        "SUV 可用於描述與追蹤，但前提是流程一致"
      ]
    ],
    "qc": [
      "注射是否順利，是否有 extravasation",
      "血糖是否在科內可接受範圍",
      "uptake time 是否落在 protocol 規範",
      "CT 與 PET 是否 misregistration",
      "scan range 是否符合臨床問題",
      "reconstruction preset 是否與科內固定版本一致"
    ],
    "pitfalls": [
      "注射滲漏",
      "褐色脂肪或肌肉攝取",
      "發炎、感染、術後變化",
      "金屬與 CT AC artifact",
      "呼吸造成肺底 / 肝頂配準誤差"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "禁食時間、血糖、胰島素 / 降糖藥、劇烈運動與保暖狀態",
      "注射時間、開始收像時間與 uptake time",
      "scan range、arms up / down、time / bed",
      "CT 模式（AC-only 或診斷 CT、是否使用對比劑）",
      "reconstruction preset 與定量指標（SUVbw 或 SUL）",
      "是否加做診斷 CT、局部延長 bed、排尿後或延遲補拍"
    ]
  },
  "BrainPET": {
    "title": "FDG Brain PET",
    "source": "SNMMI Procedure Standard / EANM Practice Guideline for Brain [18F]FDG PET Imaging version 2.0, 2024",
    "acquisition": [
      [
        "Detector / modality",
        "brain PET / CT 或 PET / MR"
      ],
      [
        "Tracer",
        "18F-FDG"
      ],
      [
        "Patient prep",
        "禁食 4–6 小時；避免高血糖；注射前後保持安靜、低刺激、避免說話與閱讀"
      ],
      [
        "Uptake time",
        "常見約 30–60 分鐘，科內需固定"
      ],
      [
        "Position",
        "supine，頭部置中固定"
      ],
      [
        "FOV / scan range",
        "頭部"
      ],
      [
        "Scan duration",
        "多約 10–20 分鐘靜態收像"
      ],
      [
        "CT role",
        "低劑量 CT AC 可行"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "高解析 OSEM"
      ],
      [
        "Iterations / subsets",
        "依 system preset 固定"
      ],
      [
        "Attenuation correction",
        "CT AC 或 MR-based AC"
      ],
      [
        "Scatter correction",
        "vendor preset"
      ],
      [
        "Resolution recovery / PSF",
        "視系統可用"
      ],
      [
        "Reorientation",
        "標準腦部 reorientation"
      ],
      [
        "Quantification",
        "若做 z-score 或半定量，需用固定 database 與 pipeline"
      ]
    ],
    "qc": [
      "注射與等待期環境是否符合 protocol",
      "頭部固定是否穩定",
      "raw data 是否有 motion",
      "使用的定量軟體與 normal database 是否一致"
    ],
    "pitfalls": [
      "高血糖",
      "頭部 motion",
      "注射等待期病人講話、哭泣、咀嚼或緊張",
      "過度平滑造成皮質細節下降"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "禁食時間、血糖、注射與等待期環境控制",
      "注射時間、開始收像時間與 uptake time",
      "頭部固定方式、收像時間與是否鎮靜",
      "CT AC 或 MR-based AC 的採用流程",
      "reconstruction preset、reorientation 規則與使用的 normal database / quantitation pipeline"
    ]
  },
  "POSLUMA": {
    "title": "PSMA PET / CT",
    "source": "Fendler WP, et al. *PSMA PET / CT: joint EANM procedure guideline / SNMMI procedure standard for prostate cancer imaging 2.0*. Eur J Nucl Med Mol Imaging. 2023;50(5):1466-1486. doi:10.1007 / s00259-022-06089-w. PMID: 36604326；Rowe SP, et al. *Prostate-specific Membrane Antigen Reporting and Data System Version 2.0*. Eur Urol. 2023;84(5):491-502. doi:10.1016 / j.eururo.2023.06.008. PMID: 37414701；Hennrich U, et al. *Revolutionizing Prostate Cancer Detection: The Role of Approved PSMA-PET Imaging Agents*. Pharmaceuticals (Basel). 2025;18(6):906. doi:10.3390 / ph18060906. PMID: 40573302；Jani AB, et al. *Diagnostic Performance and Safety of 18F-rhPSMA-7.3 Positron Emission Tomography in Men With Suspected Prostate Cancer Recurrence: Results From a Phase 3, Prospective, Multicenter Study (SPOTLIGHT).* J Urol. 2023;210(2):299-311. doi:10.1097 / JU.0000000000003493. PMID: 37126069；Schuster DM, et al. *True-Positive 18F-Flotufolastat Lesions in Patients with Prostate Cancer Recurrence with Baseline-Negative Conventional Imaging: Results from the Prospective, Phase 3, Multicenter SPOTLIGHT Study.* J Nucl Med. 2024;65(7):1080-1086. doi:10.2967 / jnumed.123.267271. PMID: 38782456；Rizzo A, et al. *The Homunculus of unspecific bone uptakes associated with PSMA-targeted tracers: a systematic review-based definition*. Eur J Nucl Med Mol Imaging. 2024;51(12):3753-3764. doi:10.1007 / s00259-024-06797-5. PMID: 38884773；DailyMed / FDA labels checked on 2026-06-03: POSLUMA (flotufolastat F 18), PYLARIFY (piflufolastat F 18 / DCFPyL), gallium Ga 68 gozetotide",
    "acquisition": [
      [
        "Detector / modality",
        "PET / CT"
      ],
      [
        "Tracer",
        "報告中必須明列使用的 PSMA radiopharmaceutical，例如 18F-flotufolastat、18F-DCFPyL、68Ga-PSMA-11、18F-PSMA-1007"
      ],
      [
        "Patient prep",
        "一般無須禁食；鼓勵補水，掃描前與掃描後排尿；若要釐清骨盆或前列腺窩，可依院內流程考慮利尿、延遲相或排尿後補拍"
      ],
      [
        "Uptake time",
        "tracer-specific；POSLUMA 官方建議注射後約 60 分鐘開始影像，68Ga-PSMA-11 常見 50–100 分鐘，18F-DCFPyL 約 60 分鐘"
      ],
      [
        "Position",
        "supine"
      ],
      [
        "FOV / scan range",
        "skull vertex 或 skull base 至 mid-thigh；高風險或問題導向時可全身"
      ],
      [
        "Time / bed",
        "多數系統約 2–4 分鐘 / bed，需配合活度與重建策略"
      ],
      [
        "CT role",
        "至少 low-dose CT 作 AC / localization；若臨床問題需要，可合併診斷 CT 或對比增強 CT"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "TOF OSEM 或 vendor validated equivalent"
      ],
      [
        "Iterations / subsets",
        "依 scanner validated preset 固定，不建議跨時期任意切換"
      ],
      [
        "Attenuation correction",
        "CT AC"
      ],
      [
        "Scatter correction",
        "vendor preset"
      ],
      [
        "Resolution recovery / PSF",
        "可用時固定啟用策略，追蹤比較需一致"
      ],
      [
        "Quantification",
        "SUV 可作描述與追蹤輔助，但跨藥物、跨重建版本與跨掃描時序比較時要保守"
      ]
    ],
    "qc": [
      "tracer 名稱、實際活度、注射時間、開始收像時間是否完整記錄",
      "uptake time 是否符合該 tracer 與院內 protocol",
      "是否有足夠補水與排尿，特別是骨盆判讀情境",
      "PET / CT 是否 misregistration，尤其橫膈、膀胱與體動區域",
      "是否有注射外滲、局部污染、金屬 artifact 或尿液造成的假影",
      "若為追蹤檢查，是否維持相同 tracer、相近 uptake time 與相同重建 preset"
    ],
    "pitfalls": [
      "生理性高攝取：淚腺、唾液腺、腎臟、輸尿管、膀胱、肝、脾、小腸",
      "交感神經節：celiac、stellate、sacral ganglia 可誤判為淋巴結",
      "尿液與 ureter activity：前列腺窩、膀胱旁、pelvic node 判讀最常受影響",
      "發炎、感染、肉芽組織、骨折修復、退化性骨病灶可假陽性",
      "18F-PSMA-1007 非特異性骨 uptake 特別常見，肋骨與骨盆最典型",
      "負向掃描不能排除微小病灶、低 PSMA 表現病灶或去分化腫瘤",
      "治療時序會改變攝取，ADT 早期 flare 或前次治療效應不可忽略"
    ],
    "localFixedFields": [
      "tracer 種類與商品名",
      "注射活度、注射時間、開始收像時間與實際 uptake time",
      "補水、排尿、是否加做利尿或延遲影像",
      "scan range、arms up / down、time / bed",
      "CT 模式（AC-only、診斷 CT、是否對比劑）",
      "重建 preset 與量化方法",
      "是否有前次治療、ADT、近期 biopsy、手術、放療或感染資訊"
    ]
  },
  "Ga68DOTATOC": {
    "title": "SSTR PET / CT",
    "source": "SNMMI Procedure Standard / EANM Practice Guideline for SSTR PET Imaging, 2022",
    "acquisition": [
      [
        "Detector / modality",
        "PET / CT"
      ],
      [
        "Tracer",
        "68Ga-DOTATATE / DOTATOC / DOTANOC 等"
      ],
      [
        "Patient prep",
        "一般不需嚴格禁食；追蹤時需保持流程一致"
      ],
      [
        "Uptake time",
        "多約 45–90 分鐘區間"
      ],
      [
        "Position",
        "supine"
      ],
      [
        "FOV / scan range",
        "skull base 或 vertex 至 mid-thigh；必要時全身"
      ],
      [
        "Time / bed",
        "多約 2–4 分鐘 / bed"
      ],
      [
        "CT role",
        "低劑量 CT AC 基本； staging 時可加診斷 CT"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "TOF OSEM 常見"
      ],
      [
        "Iterations / subsets",
        "依 vendor preset"
      ],
      [
        "Attenuation correction",
        "CT AC"
      ],
      [
        "Scatter correction",
        "vendor preset"
      ],
      [
        "Resolution recovery / PSF",
        "視系統可用"
      ],
      [
        "Quantification",
        "SUV 可輔助追蹤，但需同流程比較"
      ]
    ],
    "qc": [
      "tracer 與等待時間是否記錄完整",
      "scan range 是否足夠涵蓋已知 / 疑似病灶分布",
      "CT-PET 是否配準良好",
      "是否需要額外局部延長或局部高解析補強"
    ],
    "pitfalls": [
      "脾臟、肝、腎上腺、腎臟與尿路生理攝取",
      "炎症或非 NET 病灶的受體表現",
      "過強 PSF 視覺上放大小病灶"
    ],
    "localFixedFields": [
      "tracer 種類與實際活度",
      "注射時間、開始收像時間與 uptake time",
      "scan range、arms up / down、time / bed",
      "CT 模式（AC-only 或 staging 診斷 CT、是否使用對比劑）",
      "reconstruction preset 與定量指標",
      "是否加做局部高解析、延長 bed 或延遲補拍"
    ]
  },
  "NaFPET": {
    "title": "18F-NaF PET / CT",
    "source": "SNM guideline for Sodium 18F-Fluoride with PET / CT Bone Scans 1.1；SNM Guideline for Sodium 18F-Fluoride PET / CT Bone Scans PDF",
    "acquisition": [
      [
        "Detector / modality",
        "PET / CT"
      ],
      [
        "Tracer",
        "18F-sodium fluoride"
      ],
      [
        "Patient prep",
        "補水；掃描前排尿"
      ],
      [
        "Uptake time",
        "常見約 45–60 分鐘；科內需固定"
      ],
      [
        "Position",
        "supine 為主；必要時記錄 arms up / down"
      ],
      [
        "FOV / scan range",
        "依臨床做全身或 skull vertex 至 feet / mid-thigh"
      ],
      [
        "Time / bed",
        "多約 2–4 分鐘 / bed，依系統與體型調整"
      ],
      [
        "CT role",
        "AC / localization 基本；必要時升級診斷 CT"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "TOF OSEM 常見"
      ],
      [
        "Iterations / subsets",
        "依 vendor validated preset 固定"
      ],
      [
        "Attenuation correction",
        "CT AC"
      ],
      [
        "Scatter correction",
        "vendor preset"
      ],
      [
        "Resolution recovery / PSF",
        "視系統可用"
      ],
      [
        "Quantification",
        "SUV 可描述性使用，但不應單獨下診斷"
      ]
    ],
    "qc": [
      "CT 與 PET 是否明顯 misregistration",
      "膀胱與尿路高活性是否干擾骨盆判讀",
      "注射是否有 extravasation",
      "掃描範圍是否完整覆蓋臨床需求"
    ],
    "pitfalls": [
      "退化性骨改變與良性骨病灶",
      "尿路高活性鄰近骨盆病灶",
      "金屬與 CT AC artifact"
    ],
    "localFixedFields": [
      "uptake time",
      "scan range",
      "time / bed",
      "CT 模式",
      "reconstruction preset"
    ]
  },
  "Bone": {
    "title": "骨骼掃描 Bone Scintigraphy",
    "source": "SNMMI Practice Guideline for Bone Scintigraphy 4.0",
    "acquisition": [
      [
        "Detector / modality",
        "planar whole-body，可加 SPECT / CT"
      ],
      [
        "Tracer",
        "Tc-99m labeled diphosphonates"
      ],
      [
        "Patient prep",
        "補水；注射後至 delayed imaging 間鼓勵排尿"
      ],
      [
        "Phase 1",
        "注射當下 dynamic flow"
      ],
      [
        "Phase 2",
        "注射後立即至 10 分鐘內 blood pool"
      ],
      [
        "Phase 3",
        "注射後 2–4 小時 delayed skeletal images"
      ],
      [
        "Matrix",
        "blood pool 常見 128x128 或更高"
      ],
      [
        "Counts goal",
        "blood pool 約 300k / image 常見；extremity 可較低"
      ],
      [
        "CT role",
        "SPECT / CT 用於定位與提升特異性"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "若做 SPECT，多為 iterative reconstruction"
      ],
      [
        "Attenuation correction",
        "SPECT / CT 時可用 CT AC"
      ],
      [
        "Scatter correction",
        "視系統可用"
      ],
      [
        "Resolution recovery / PSF",
        "視系統可用"
      ],
      [
        "Quantification",
        "以視覺與解剖配對為主"
      ]
    ],
    "qc": [
      "注射是否有 extravasation",
      "delayed imaging 時間是否足夠",
      "尿液污染是否已辨識",
      "是否真的需要 SPECT / CT 補定位"
    ],
    "pitfalls": [
      "尿液污染",
      "退化性變化 vs 骨轉移",
      "延遲時間過短造成背景高",
      "局部 spot / SPECT 缺乏對位時過度解讀"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ]
  },
  "MPI_Tc99m": {
    "title": "心肌灌流 SPECT 臨床指引 (Tc-99m MPI SPECT)",
    "source": "ASNC, *Single Photon Emission Computed Tomography (SPECT) Myocardial Perfusion Imaging Guidelines: Instrumentation, Acquisition, Processing, and Interpretation* (2018)；ASNC, *Quality Metrics for Single-Photon Emission Computed Tomography Myocardial Perfusion Imaging: An ASNC Information Statement* (2023)；EANM, *EANM procedural guidelines for radionuclide myocardial perfusion imaging with SPECT and SPECT / CT* (2015)；ASNC, *Standardized Reporting of Nuclear Cardiology Procedures* (2017)；ASNC / AHA / ACC, *Reporting of Myocardial Perfusion Imaging Tests Quick Reference* (2024)",
    "acquisition": [],
    "processing": [],
    "qc": [],
    "pitfalls": [],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ]
  },
  "CardiacPET": {
    "title": "PET Myocardial Perfusion Imaging",
    "source": "SNMMI / EANM / ASNC / ACNM Guideline for 18F-Flurpiridaz PET Myocardial Perfusion Imaging and Blood Flow Quantitation, 2025；ASNC PET Quick Reference Guide, 2024",
    "acquisition": [
      [
        "Detector / modality",
        "PET / CT"
      ],
      [
        "Tracer",
        "Rb-82、N-13 ammonia、18F-flurpiridaz"
      ],
      [
        "Patient prep",
        "依 stress 與藥物規範；多為 pharmacologic stress"
      ],
      [
        "Position",
        "supine"
      ],
      [
        "CT role",
        "低劑量 CT AC 幾乎為標配"
      ],
      [
        "Acquisition",
        "static 或 dynamic + static，視是否做 MBF / MFR"
      ],
      [
        "Gating",
        "可加 ECG gating"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "TOF OSEM 常見"
      ],
      [
        "Iterations / subsets",
        "依 vendor validated preset"
      ],
      [
        "Attenuation correction",
        "CT AC"
      ],
      [
        "Scatter correction",
        "vendor preset"
      ],
      [
        "Motion correction",
        "視系統可用"
      ],
      [
        "Quantification",
        "MBF / MFR、perfusion、EF 等"
      ]
    ],
    "qc": [
      "stress 是否達標",
      "注射時序與 dynamic framing 是否正確",
      "CT-PET 是否 misregistration",
      "flow quantitation software 是否為 validated pipeline"
    ],
    "pitfalls": [
      "dynamic acquisition 起始錯誤",
      "CT AC 對位不良",
      "不同 tracer / 不同流程定量結果硬比"
    ],
    "localFixedFields": [
      "tracer 種類與實際活度",
      "stress 藥物 / 運動條件、停止咖啡因與用藥規則",
      "注射時間、dynamic framing、開始收像時間",
      "是否做 dynamic + static、是否加 ECG gating",
      "CT AC 模式與配準檢查流程",
      "reconstruction preset 與 MBF / MFR quantitation software pipeline"
    ]
  },
  "CardiacAmyloid": {
    "title": "Cardiac Amyloidosis Imaging（PYP / DPD / HMDP）",
    "source": "Cardiac Amyloidosis Imaging | SNMMI；ASNC / AHA / ASE / EANM / HFSA / ISA / SCMR / SNMMI Expert Consensus Recommendations, 2019",
    "acquisition": [
      [
        "Detector / modality",
        "planar + SPECT 或 SPECT / CT"
      ],
      [
        "Tracer",
        "99mTc-PYP；不同地區亦可用 DPD / HMDP"
      ],
      [
        "Patient prep",
        "一般無特殊禁食要求"
      ],
      [
        "Uptake time",
        "常見 1 小時；部分 protocol 會在 3 小時補拍"
      ],
      [
        "Position",
        "supine"
      ],
      [
        "Planar views",
        "anterior 胸部基本"
      ],
      [
        "SPECT",
        "強烈建議加入，用於區分血池與心肌攝取"
      ],
      [
        "Matrix",
        "planar / SPECT 常見 128x128"
      ],
      [
        "Orbit / arc",
        "cardiac SPECT 常規 arc 或 360° 視系統"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "iterative reconstruction 常見"
      ],
      [
        "Attenuation correction",
        "視是否有 SPECT / CT"
      ],
      [
        "Reorientation",
        "cardiac standard planes"
      ],
      [
        "Quantification",
        "H / CL ratio、視覺分級；但需與 SPECT 結果一起看"
      ]
    ],
    "qc": [
      "是否有做 SPECT 或 SPECT / CT",
      "血池殘留是否明顯",
      "平面 ROI 放置是否標準",
      "掃描時間點是否固定在科內採用版本"
    ],
    "pitfalls": [
      "只有 planar 沒有 tomographic 確認",
      "血池殘留誤判為心肌陽性",
      "rib uptake / soft tissue overlap"
    ],
    "localFixedFields": [
      "1 小時或 3 小時 protocol 的採用規則",
      "是否所有陽性疑問例都加做 SPECT 或 SPECT / CT",
      "H / CL ratio 的 ROI 放置方式",
      "planar 與 tomographic 結果不一致時的判讀規則"
    ]
  },
  "Thyroid": {
    "title": "Thyroid Uptake 與 Thyroid Scintigraphy",
    "source": "EANM / SNMMI guideline for Radio-Iodine Uptake and Thyroid Scintigraphy v3.0；ACR / SNMMI / SPR Practice Guideline for the Performance of Thyroid Scintigraphy and Uptake Measurements",
    "acquisition": [
      [
        "Detector / modality",
        "planar small-organ imaging"
      ],
      [
        "Tracer",
        "Tc-99m pertechnetate、I-123、特定情境 I-131"
      ],
      [
        "Patient prep",
        "確認含碘顯影劑、amiodarone、甲狀腺藥物與其他干擾因素"
      ],
      [
        "Position",
        "頸部伸展、chin up"
      ],
      [
        "Collimator",
        "Tc-99m 多用 LEHR；I-123 常用 MEGP 或依系統要求"
      ],
      [
        "Matrix",
        "128x128 或 256x256"
      ],
      [
        "Zoom / pixel size",
        "讓 thyroid 充滿主要 FOV"
      ],
      [
        "Views",
        "anterior 為基本；必要時 oblique；pinhole 常用於細節"
      ],
      [
        "Counts goal",
        "常見約 100k–300k，依細節需求調整"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "不適用，主要為 planar"
      ],
      [
        "Quantification",
        "uptake test 需固定標準源、背景與時間點"
      ],
      [
        "ROI",
        "若做 uptake / 定量，需固定頸部與背景 ROI 幾何"
      ]
    ],
    "qc": [
      "是否有近期碘負荷或干擾藥物",
      "標準源與時間點是否完整記錄",
      "下巴與頸部位置是否理想",
      "是否需要 pinhole 補細節"
    ],
    "pitfalls": [
      "食道 / 口腔污染",
      "下巴遮擋上極",
      "pinhole 幾何不一致",
      "uptake 流程只記結果不記時間與標準源條件"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ]
  },
  "Parathyroid": {
    "title": "Parathyroid Scintigraphy",
    "source": "SNMMI guideline for Parathyroid Scintigraphy 4.0；SNM Practice Guideline for Parathyroid Scintigraphy 4.0 PDF",
    "acquisition": [
      [
        "Detector / modality",
        "planar + SPECT / CT"
      ],
      [
        "Tracer",
        "Tc-99m sestamibi 為主"
      ],
      [
        "Technique",
        "dual-phase 或 dual-isotope subtraction"
      ],
      [
        "Position",
        "頭頸固定穩定"
      ],
      [
        "Planar matrix",
        "128x128 常見"
      ],
      [
        "SPECT matrix",
        "128x128 常見"
      ],
      [
        "Orbit / arc",
        "360°"
      ],
      [
        "Time / view",
        "約 20–30 秒 / stop 常見"
      ],
      [
        "CT role",
        "低劑量 CT localization"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "iterative reconstruction 常見"
      ],
      [
        "Attenuation correction",
        "SPECT / CT 時可用 CT AC"
      ],
      [
        "Reorientation",
        "頭頸標準 planes 與對位"
      ],
      [
        "Quantification",
        "以視覺定位為主"
      ]
    ],
    "qc": [
      "前後時相或雙核種影像是否對位",
      "頭頸是否有 motion",
      "是否涵蓋頸部至上縱膈",
      "是否需要 SPECT / CT 補定位"
    ],
    "pitfalls": [
      "甲狀腺結節干擾",
      "motion 造成假性殘留 / 消失",
      "只看 planar 忽略 tomographic localization"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ]
  },
  "MIBG": {
    "title": "123I / 131I-MIBG Scintigraphy",
    "source": "131I / 123I-Metaiodobenzylguanidine scintigraphy: EANM guideline for tumour imaging, SNMMI endorsement",
    "acquisition": [
      [
        "Detector / modality",
        "whole-body planar，可加 SPECT / CT"
      ],
      [
        "Tracer",
        "123I-MIBG 診斷最常用；特定情況可見 131I-MIBG"
      ],
      [
        "Patient prep",
        "thyroid blockade；停用干擾藥物；必要時補充用藥清單"
      ],
      [
        "Uptake time",
        "常見 24 小時影像；必要時延至 48 小時"
      ],
      [
        "Position",
        "whole-body anterior / posterior"
      ],
      [
        "Collimator",
        "123I 建議 MEGP；131I 需高能量對應 collimator"
      ],
      [
        "Energy window",
        "依核種設定；123I 常以 159 keV 為主"
      ],
      [
        "Matrix",
        "whole-body 依系統固定； spot / SPECT 通常 128x128 常見"
      ],
      [
        "CT role",
        "SPECT / CT 用於病灶定位與解剖配對"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "若加 SPECT，多用 iterative reconstruction"
      ],
      [
        "Attenuation correction",
        "SPECT / CT 時可做 CT AC"
      ],
      [
        "Scatter correction",
        "依系統與核種條件"
      ],
      [
        "Quantification",
        "多為視覺與半定量輔助，不同中心方法差異大"
      ]
    ],
    "qc": [
      "thyroid blockade 是否完成",
      "干擾藥物是否停用或至少完整記錄",
      "collimator 是否與核種匹配",
      "whole-body 掃描範圍是否完整",
      "是否需要延遲影像或 SPECT / CT 補定位"
    ],
    "pitfalls": [
      "用錯 collimator",
      "生理性唾液腺、肝臟、膀胱與腸道分布",
      "藥物干擾導致假陰性",
      "只做 whole-body 不做局部 tomographic 補強"
    ],
    "localFixedFields": [
      "thyroid blockade 流程",
      "干擾藥物停用清單",
      "24 小時與 48 小時影像的使用條件",
      "whole-body 後何時加做局部 SPECT / CT"
    ]
  },
  "Salivary": {
    "title": "Salivary gland scintigraphy",
    "source": "整理自 2016 ACR/EULAR Sjogren 分類準則後續影像評論、2024 健康族群唾液腺動態常模研究與近年 salivary scintigraphy 文獻。",
    "acquisition": [
      "常見檢前至少禁食 2 小時並維持基本補水，避免口腔與胃部背景差異過大。",
      "Tc-99m pertechnetate 注射後以 anterior 頭頸連續動態收像，頭頸固定與左右視野完整比「補拍更多張」更重要。",
      "刺激物種類、容量與給予時間點要固定；許多 protocol 以 20 分鐘給檸檬汁，再持續追蹤排出與再累積。"
    ],
    "processing": [
      "先看雙側腮腺與頜下腺是否對稱累積，再看刺激後是否出現明顯下降與後續再累積。",
      "視覺型態與 time-activity curve 要一起讀，不能只看單張最亮或最暗的影像。",
      "若有定量，ROI 畫法、background 位置與指標定義需固定，否則不同病人與不同時間點無法比較。"
    ],
    "qc": [
      "臨床問題是否清楚",
      "選的 tracer 是否真的回答該問題",
      "病人準備是否完成",
      "是否有近期造影劑、藥物、食物或手術影響判讀",
      "是否需排尿、補水、停藥、 thyroid blockade、 premedication",
      "注射是否順利，是否疑似 extravasation",
      "detector / camera / CT 是否通過當日 QC",
      "是否選對 collimator、energy window、matrix、zoom",
      "病人是否能穩定維持姿勢",
      "是否需要固定帶、枕頭、膝下墊、 head holder",
      "先看 raw data，不要只看重建結果",
      "是否有 motion、截切、金屬、污染、注射滲漏",
      "重建參數是否與科內 preset 一致",
      "report 中是否完整記錄 tracer、activity、注射時間、掃描時間與特殊事件"
    ],
    "pitfalls": [
      "是否有 TOF",
      "是否有 PSF",
      "是否有 penalized likelihood",
      "CT AC 是否成功",
      "是否有 metal artifact / respiratory misregistration"
    ],
    "localFixedFields": [
      "禁食與補水規則",
      "刺激物種類與刺激時間點",
      "dynamic frame 長度與總收像時間",
      "ROI 與排出分率計算方法"
    ],
    "note": "唾液腺掃描的重點在雙側大唾液腺的攝取、刺激後排出與再累積節奏；若刺激物與時間點不固定，曲線就失去比較價值。"
  },
  "DTPA": {
    "title": "Renal Dynamic Scintigraphy（MAG3 / DTPA）",
    "source": "SNMMI / EANM Renal Scintigraphy in Adults, 2018",
    "acquisition": [
      [
        "Detector / modality",
        "dynamic planar renal scan"
      ],
      [
        "Tracer",
        "MAG3 或 DTPA"
      ],
      [
        "Patient prep",
        "補水；開始前先排尿"
      ],
      [
        "Position",
        "posterior 為主；移植腎 / 異位腎用 anterior"
      ],
      [
        "Collimator",
        "LEHR 或 general-purpose"
      ],
      [
        "Matrix",
        "64x64 或 128x128"
      ],
      [
        "Perfusion phase",
        "1–2 秒 / frame，1–2 分鐘"
      ],
      [
        "Functional phase",
        "10–15 秒 / frame，約 5 分鐘"
      ],
      [
        "Excretion phase",
        "20–30 秒 / frame，至總長 20–30 分鐘"
      ],
      [
        "Post-void image",
        "建議加做"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "不適用，主要為 dynamic planar"
      ],
      [
        "Quantification",
        "differential function、Tmax、drainage pattern 等"
      ],
      [
        "ROI",
        "腎臟與 background ROI 需固定邏輯"
      ]
    ],
    "qc": [
      "注射是否像 bolus、是否有 extravasation",
      "病人是否先排尿",
      "raw cine 是否完整",
      "ROI 是否避開肝脾 / 腸道重疊"
    ],
    "pitfalls": [
      "hydration 不足",
      "bladder 充滿未排",
      "extravasation",
      "只看數值不看原始影像"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ]
  },
  "MAG3": {
    "title": "Diuretic Renography",
    "source": "SNMMI / EANM guideline for Diuretic Renal Scintigraphy in Adults With Suspected Upper Urinary Tract Obstruction；成人 renal scintigraphy guideline",
    "acquisition": [
      [
        "Detector / modality",
        "dynamic renal scan"
      ],
      [
        "Tracer",
        "MAG3 最常用"
      ],
      [
        "Patient prep",
        "良好 hydration；評估 bladder 狀態；必要時導尿"
      ],
      [
        "Position",
        "固定、舒適、可重現"
      ],
      [
        "Protocol family",
        "F+20、F+0、F-15 等，科內應固定版本"
      ],
      [
        "Matrix",
        "64x64 或 128x128"
      ],
      [
        "Dynamic framing",
        "依 renography 主流程"
      ],
      [
        "Post-void image",
        "強烈建議"
      ]
    ],
    "processing": [
      [
        "Quantification",
        "drainage pattern、T1 / 2、relative function 等"
      ],
      [
        "ROI",
        "collecting system 與整腎 ROI 需依 protocol 一致"
      ]
    ],
    "qc": [
      "利尿劑給藥時間是否完整記錄",
      "hydration 是否足夠",
      "bladder 是否造成下尿路干擾",
      "使用的是哪一個 protocol family 是否清楚"
    ],
    "pitfalls": [
      "protocol 混用",
      "腎功能太差時 T1 / 2 過度解讀",
      "巨大膀胱或排尿不佳"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ]
  },
  "DMSA": {
    "title": "DMSA Renal Cortical Scintigraphy",
    "source": "Pediatric [99mTc]Tc-DMSA Renal Cortical Scintigraphy: An Update, 2021；SNMMI / EANM Renal Scintigraphy in Adults, 2018",
    "acquisition": [
      [
        "Detector / modality",
        "planar renal cortical imaging，可加 SPECT"
      ],
      [
        "Tracer",
        "Tc-99m DMSA"
      ],
      [
        "Patient prep",
        "補水；減少病人移動"
      ],
      [
        "Timing",
        "注射後 2–4 小時；腎功能差可更晚"
      ],
      [
        "Position",
        "supine"
      ],
      [
        "Collimator",
        "LEHR、LEUHR 或 pinhole"
      ],
      [
        "Matrix",
        "128x128 或 256x256"
      ],
      [
        "Zoom / pixel size",
        "目標約 2–4 mm"
      ],
      [
        "Counts goal",
        "每 view 至少約 200k 或固定 5–10 分鐘"
      ],
      [
        "Views",
        "posterior、雙 posterior oblique，必要時 anterior"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "若做 SPECT，多為 iterative reconstruction"
      ],
      [
        "Attenuation correction",
        "視是否有 SPECT / CT"
      ],
      [
        "Quantification",
        "differential cortical function、scar / defect pattern"
      ]
    ],
    "qc": [
      "是否有 motion blur",
      "注射是否順利",
      "是否出現異常高肝背景",
      "視野是否涵蓋異位或旋轉異常腎臟需求"
    ],
    "pitfalls": [
      "motion blur",
      "pinhole 幾何不一致",
      "肝背景偏高暗示品質問題",
      "沒補 appropriate oblique / anterior 導致解剖誤判"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ]
  },
  "Gastric": {
    "title": "Gastric Emptying Scintigraphy",
    "source": "Consensus Recommendations for Gastric Emptying Scintigraphy；Gastric Emptying Scintigraphy 2024: Still A Need for Compliance with Published Guidelines",
    "acquisition": [
      [
        "Detector / modality",
        "planar serial imaging"
      ],
      [
        "Tracer",
        "Tc-99m sulfur colloid 標記固體餐"
      ],
      [
        "Patient prep",
        "空腹至少 6 小時；影響胃排空藥物通常停 48 小時"
      ],
      [
        "Standard meal",
        "低脂 egg-white meal"
      ],
      [
        "Position",
        "站立或固定姿勢，科內需一致"
      ],
      [
        "Collimator",
        "LEAP 或 LEHR"
      ],
      [
        "Energy window",
        "140 keV 20% window"
      ],
      [
        "Matrix",
        "128x128"
      ],
      [
        "Imaging schedule",
        "0、1、2、4 小時至少各收 anterior + posterior 1 分鐘"
      ]
    ],
    "processing": [
      [
        "Quantification",
        "anterior / posterior geometric mean"
      ],
      [
        "ROI",
        "胃 ROI 需完整且避開鄰近腸道"
      ],
      [
        "Endpoints",
        "各時間點胃殘留，4 小時尤重要"
      ]
    ],
    "qc": [
      "標準餐是否完整吃完",
      "影響胃排空藥物是否停用或完整記錄",
      "各時間點是否準時",
      "是否真的做到 4 小時"
    ],
    "pitfalls": [
      "病人沒吃完餐",
      "只做到 2 小時",
      "ROI 把小腸納入",
      "忽略藥物影響"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ]
  },
  "Biliary": {
    "title": "Hepatobiliary Scintigraphy / HIDA",
    "source": "SNM guideline for Hepatobiliary Scintigraphy 4.0；Appropriate Use Criteria for Hepatobiliary Scintigraphy in Abdominal Pain",
    "acquisition": [
      [
        "Detector / modality",
        "dynamic planar，可加 SPECT / CT"
      ],
      [
        "Tracer",
        "Tc-99m mebrofenin / DISIDA 類"
      ],
      [
        "Patient prep",
        "常以 4–6 小時禁食為宜；需記錄 opioids、TPN、肝功能狀態"
      ],
      [
        "Position",
        "supine"
      ],
      [
        "View",
        "anterior 基本，必要時 oblique / lateral"
      ],
      [
        "Matrix",
        "128x128 常見"
      ],
      [
        "Dynamic framing",
        "注射後立即開始；常見 1 frame / min，至少 60 分鐘"
      ],
      [
        "CT role",
        "SPECT / CT 於特定定位問題有幫助"
      ]
    ],
    "processing": [
      [
        "Quantification",
        "若做 GBEF，需固定刺激方式與演算法"
      ],
      [
        "ROI",
        "肝、膽囊、小腸等 ROI 視 protocol 需要"
      ]
    ],
    "qc": [
      "禁食時間是否在合理範圍",
      "opioids 或其他干擾因素是否記錄",
      "dynamic 是否完整保留",
      "若做 CCK / sincalide / morphine，給藥條件是否標準化"
    ],
    "pitfalls": [
      "禁食過短或過長",
      "opioid 干擾",
      "肝功能異常導致延遲卻誤判",
      "GBEF protocol 混用"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ]
  },
  "GIBleed": {
    "title": "Gastrointestinal Bleeding Scintigraphy",
    "source": "Gastrointestinal Bleeding Scintigraphy 3.0；2024 PDF procedure standard",
    "acquisition": [
      [
        "Detector / modality",
        "dynamic planar serial imaging"
      ],
      [
        "Tracer",
        "Tc-99m labeled autologous RBC"
      ],
      [
        "Patient prep",
        "依急重症情境安排，重點是盡快開始標準化收像"
      ],
      [
        "Position",
        "supine"
      ],
      [
        "View",
        "anterior abdomen / pelvis 基本"
      ],
      [
        "Matrix",
        "128x128 常見"
      ],
      [
        "Start",
        "注射後立即動態收像"
      ],
      [
        "Delayed imaging",
        "必要時延伸至較晚時間點"
      ]
    ],
    "processing": [
      [
        "Quantification",
        "以動態模式辨識為主"
      ],
      [
        "Review",
        "必看 raw dynamic sequence，不可只看靜態截圖"
      ]
    ],
    "qc": [
      "RBC 標記流程是否完成",
      "dynamic 是否從注射後立即開始",
      "是否完整保留足夠時間序列",
      "疑似陽性灶是否符合移動模式"
    ],
    "pitfalls": [
      "泌尿系統活性",
      "free pertechnetate",
      "血管 / 子宮 / 脾臟等固定結構",
      "只有靜態影像無法確認腸道移動"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ]
  },
  "Liver": {
    "title": "Liver-Spleen Scintigraphy",
    "source": "ACR / SNMMI / SPR Practice Guideline for the Performance of Liver and Spleen Scintigraphy",
    "acquisition": [
      [
        "Detector / modality",
        "planar，可加 SPECT / CT"
      ],
      [
        "Tracer",
        "99mTc-sulfur colloid 或依適應症調整"
      ],
      [
        "Patient prep",
        "通常無特殊準備"
      ],
      [
        "Position",
        "supine"
      ],
      [
        "Views",
        "anterior、posterior、oblique；視問題加局部"
      ],
      [
        "Matrix",
        "128x128 常見"
      ],
      [
        "Counts / time",
        "以足夠顯示肝脾輪廓與 focal defect 為原則"
      ],
      [
        "CT role",
        "若做 SPECT / CT，以定位 accessory spleen 或異位脾組織特別有用"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "若加 SPECT，多為 iterative reconstruction"
      ],
      [
        "Attenuation correction",
        "視是否有 SPECT / CT"
      ],
      [
        "Quantification",
        "多以視覺與分布描述為主"
      ]
    ],
    "qc": [
      "臨床問題是否真的適合此檢查",
      "是否需要 SPECT / CT 補定位",
      "視野是否完整包含疑似 accessory spleen 區域"
    ],
    "pitfalls": [
      "局部截切",
      "腸道、腎臟或其他解剖結構誤認",
      "沒有搭配對位影像就過度解讀"
    ],
    "localFixedFields": [
      "何時只做 planar、何時加做 SPECT / CT",
      "視野是否固定包含全肝脾或疑問區",
      "tracer 選擇與適應症分流"
    ]
  },
  "Brain": {
    "title": "Brain Perfusion SPECT",
    "source": "Brain Perfusion SPECT Using 99mTc Radiopharmaceuticals 3.0",
    "acquisition": [
      [
        "Detector / modality",
        "brain SPECT"
      ],
      [
        "Tracer",
        "Tc-99m HMPAO 或 ECD"
      ],
      [
        "Patient prep",
        "安靜、昏暗、低刺激；注射前後避免交談與閱讀"
      ],
      [
        "Position",
        "supine，頭部置中固定"
      ],
      [
        "Matrix",
        "128x128 常見"
      ],
      [
        "Orbit",
        "360°"
      ],
      [
        "Step angle",
        "約 3° 常見"
      ],
      [
        "Radius",
        "盡量小"
      ],
      [
        "Duration",
        "多約 20–30 分鐘，依 counts 與系統"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "iterative reconstruction 常見"
      ],
      [
        "Attenuation correction",
        "視系統與 workflow"
      ],
      [
        "Scatter correction",
        "視系統可用"
      ],
      [
        "Reorientation",
        "標準腦部 planes"
      ],
      [
        "Quantification",
        "視需要做半定量分析"
      ]
    ],
    "qc": [
      "注射環境是否符合 protocol",
      "頭部是否穩定固定",
      "raw projection / sinogram 是否有 motion",
      "重建與 reorientation 是否一致"
    ],
    "pitfalls": [
      "注射時病人受到刺激",
      "頭動",
      "過度平滑"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ]
  },
  "TRODAT": {
    "title": "DaT SPECT（123I-Ioflupane）",
    "source": "EANM / SNMMI guideline for Dopaminergic Imaging in Parkinsonian Syndromes；SNM Practice Guideline for Dopamine Transporter Imaging",
    "acquisition": [
      [
        "Detector / modality",
        "brain SPECT"
      ],
      [
        "Tracer",
        "123I-ioflupane"
      ],
      [
        "Patient prep",
        "thyroid blockade；掃描前排尿；必要時可考慮不影響結果的短效鎮靜"
      ],
      [
        "Timing",
        "注射後 3–6 小時"
      ],
      [
        "Position",
        "supine，頭部固定"
      ],
      [
        "Collimator",
        "MEGP 建議"
      ],
      [
        "Energy window",
        "159 keV ± 10%"
      ],
      [
        "Matrix",
        "128x128"
      ],
      [
        "Pixel size",
        "約 3.5–4.5 mm"
      ],
      [
        "Orbit",
        "360°"
      ],
      [
        "Step angle",
        "約 3°"
      ],
      [
        "Time / view",
        "常見 30–40 秒 / stop"
      ],
      [
        "Counts goal",
        "常見至少約 1.5 million total counts"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "iterative reconstruction 優先"
      ],
      [
        "Attenuation correction",
        "視系統與 workflow"
      ],
      [
        "Scatter correction",
        "視系統可用"
      ],
      [
        "Motion correction",
        "minor motion 可嘗試；明顯 motion 不可靠"
      ],
      [
        "Reorientation",
        "標準 striatal plane"
      ],
      [
        "Quantification",
        "視覺判讀為主，可輔助半定量"
      ]
    ],
    "qc": [
      "thyroid blockade 是否完成",
      "collimator 是否正確",
      "頭部是否穩定",
      "raw data 是否有 motion",
      "reorientation 是否標準"
    ],
    "pitfalls": [
      "用 LEHR 收 I-123",
      "頭動",
      "切片方向不標準"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ]
  },
  "LungVQ": {
    "title": "V / Q Scintigraphy",
    "source": "Pulmonary Scintigraphy archived guideline；Appropriate Use Criteria for Ventilation / Perfusion Imaging in Pulmonary Embolism",
    "acquisition": [
      [
        "Detector / modality",
        "planar 多投影；許多中心已做 V / Q SPECT 或 SPECT / CT"
      ],
      [
        "Perfusion tracer",
        "Tc-99m MAA"
      ],
      [
        "Ventilation",
        "gas 或 aerosol，依院內設備"
      ],
      [
        "Patient prep",
        "視呼吸狀況與合作度調整"
      ],
      [
        "Position",
        "依 protocol 固定"
      ],
      [
        "Views",
        "標準胸部多投影；若 SPECT 則完整 tomographic acquisition"
      ],
      [
        "Matrix",
        "planar 常見 128x128"
      ],
      [
        "CT role",
        "若有 SPECT / CT，可加強定位"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "若做 SPECT，多為 iterative reconstruction"
      ],
      [
        "Attenuation correction",
        "視 SPECT / CT workflow"
      ],
      [
        "Reorientation",
        "肺部標準 planes"
      ],
      [
        "Quantification",
        "多以分布模式與 mismatch 為主"
      ]
    ],
    "qc": [
      "ventilation study 品質是否足夠",
      "aerosol 是否有中央氣道 hot spot",
      "perfusion 注射是否順利",
      "若做 SPECT / CT，是否 misregistration"
    ],
    "pitfalls": [
      "poor ventilation quality",
      "aerosol 中央沉積",
      "只靠單面投影簡化解讀"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ]
  },
  "WBCScan": {
    "title": "Leukocyte / Infection Scintigraphy",
    "source": "ACR / SNMMI / SPR Practice Guideline for the Performance of Scintigraphy for Inflammation or Infection；Society of Nuclear Medicine Procedure Guideline for 111In-Leukocyte Scintigraphy",
    "acquisition": [
      [
        "Detector / modality",
        "planar serial imaging，可加 SPECT / CT"
      ],
      [
        "Tracer",
        "In-111 leukocytes 或 Tc-99m HMPAO leukocytes"
      ],
      [
        "Patient prep",
        "依感染部位與 clinical question 安排"
      ],
      [
        "Labeling",
        "無菌、可追溯、具 QC"
      ],
      [
        "Imaging time",
        "依 tracer 與問題分早期、延遲、必要時更晚"
      ],
      [
        "CT role",
        "SPECT / CT 對定位很有幫助"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "若做 SPECT，多為 iterative reconstruction"
      ],
      [
        "Attenuation correction",
        "視 SPECT / CT workflow"
      ],
      [
        "Quantification",
        "多以序列變化與分布模式為主"
      ]
    ],
    "qc": [
      "blood handling 與 labeling QC 是否完成",
      "各時間點是否符合該 tracer protocol",
      "是否需要與 bone marrow imaging 對照",
      "raw serial images 是否完整保留"
    ],
    "pitfalls": [
      "標記品質不穩",
      "時間點選錯",
      "生理性骨髓 / 脾臟 / 腸道分布誤判",
      "忽略 lab 端可追溯紀錄"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ]
  },
  "AmyloidPET": {
    "title": "Amyloid PET",
    "source": "SNMMI Procedure Standard / EANM Practice Guideline for Amyloid PET；Updated Appropriate Use Criteria for Amyloid and Tau PET, 2025",
    "acquisition": [
      [
        "Tracer",
        "18F-florbetapir、18F-flutemetamol、18F-florbetaben 等"
      ],
      [
        "掃描時間",
        "依 tracer label，通常在注射後固定窗口內進行 10–20 分鐘靜態掃描"
      ],
      [
        "頭部固定",
        "必須嚴格，因皮質判讀高度依賴細節"
      ],
      [
        "CT / AC",
        "可使用低劑量 CT AC"
      ],
      [
        "Reconstruction",
        "高解析 OSEM，切片厚度與 smoothing 應固定"
      ]
    ],
    "processing": [
      "一定要熟悉各 tracer label 規定的 acquisition window",
      "判讀核心是灰白質分界，不是單看全腦亮不亮",
      "若做定量，需使用對應的 validated software pipeline"
    ],
    "qc": [
      "CT 與 PET 是否 misregistration",
      "注射滲漏",
      "病人 motion",
      "尿路高活性污染或局部 spillover",
      "金屬植入造成 CT AC artifact",
      "兩次追蹤檢查若重建 preset 改變，SUV 不宜直接硬比"
    ],
    "pitfalls": [
      "CT 與 PET 是否 misregistration",
      "注射滲漏",
      "病人 motion",
      "尿路高活性污染或局部 spillover",
      "金屬植入造成 CT AC artifact",
      "兩次追蹤檢查若重建 preset 改變，SUV 不宜直接硬比"
    ],
    "localFixedFields": [
      "tracer 種類與實際活度",
      "注射時間、開始收像時間與 tracer-specific acquisition window",
      "頭部固定方式與收像時間",
      "CT AC 或其他 attenuation correction 流程",
      "reconstruction preset 與 quantitation software pipeline"
    ],
    "note": "本站目前使用 PET 總覽章節整理；若未來另建單卷，再替換成專檔版。"
  },
  "MPI_Tl201": {
    "title": "Tl-201 MPI",
    "source": "",
    "acquisition": [
      "常用在 MPI、bone SPECT / CT、parathyroid、brain perfusion、DaT",
      "關鍵是：",
      "orbit 要盡量貼身",
      "view 數不能太少",
      "每 view 的 counts / seconds 要與 matrix 匹配",
      "reconstruction 與 filter 不能亂混"
    ],
    "processing": [
      "photon energy 較低且較易受衰減影響",
      "收像時間通常要比 Tc-99m protocol 長",
      "若做 redistribution / reinjection，時間點必須嚴格記錄"
    ],
    "qc": [
      "energy peaking 與 uniformity 每日 QC",
      "ECG gating 是否穩定",
      "motion review：尤其 stress 後病人較不穩",
      "AC CT 是否對位",
      "reconstruction preset 是否一致"
    ],
    "pitfalls": [
      "軟組織衰減假性缺損",
      "心律不整造成 gating 失敗",
      "subdiaphragmatic activity 干擾下壁",
      "壓力流程條件未固定，會讓前後檢查不可比。",
      "只看 AC 或只看 gated function，沒回到 raw data。"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ],
    "note": "本站目前使用心臟核醫總覽章節整理；若未來另建單卷，再替換成專檔版。"
  },
  "Salivary2": {
    "title": "Salivary Gland Scintigraphy",
    "source": "ACR / SNMMI / SPR Practice Guideline for Performance of Gastrointestinal Scintigraphy",
    "acquisition": [
      [
        "Detector / modality",
        "planar dynamic"
      ],
      [
        "Tracer",
        "Tc-99m pertechnetate"
      ],
      [
        "Patient prep",
        "避免影響唾液分泌的因素；刺激物準備一致"
      ],
      [
        "Position",
        "supine 或 seated，頭頸固定"
      ],
      [
        "View",
        "anterior 頭頸"
      ],
      [
        "Matrix",
        "128x128 常見"
      ],
      [
        "Dynamic framing",
        "依科內 protocol 固定短 frame 連續收像"
      ],
      [
        "Stimulation",
        "檸檬汁或其他刺激方式，時間點需固定"
      ]
    ],
    "processing": [
      [
        "Reconstruction family",
        "不適用，主要為 dynamic planar"
      ],
      [
        "Quantification",
        "time-activity curves、攝取與排出指標"
      ],
      [
        "ROI",
        "parotid、submandibular、background 需固定"
      ]
    ],
    "qc": [
      "刺激時間點是否記錄",
      "動態過程是否有病人移動",
      "ROI 是否一致"
    ],
    "pitfalls": [
      "頭頸 motion",
      "刺激時間點不一致",
      "只看單張影像不看 curve"
    ],
    "localFixedFields": [
      "刺激物種類",
      "刺激時間點",
      "dynamic frame 長度",
      "ROI 與 curve 分析方法"
    ],
    "note": "此頁沿用唾液腺掃描同一份技術摘要。"
  },
  "Lung": {
    "title": "Pulmonary perfusion scintigraphy",
    "source": "",
    "acquisition": [
      "常用在 thyroid、DMSA、bone whole-body、GI bleed、lung perfusion",
      "關鍵是：",
      "collimator 選對",
      "counts 足夠",
      "病人位置穩",
      "視野完整"
    ],
    "processing": [
      "後處理請先回看 raw data，再確認重建 preset 與對位品質。"
    ],
    "qc": [
      "臨床問題是否清楚",
      "選的 tracer 是否真的回答該問題",
      "病人準備是否完成",
      "是否有近期造影劑、藥物、食物或手術影響判讀",
      "是否需排尿、補水、停藥、 thyroid blockade、 premedication",
      "注射是否順利，是否疑似 extravasation",
      "detector / camera / CT 是否通過當日 QC",
      "是否選對 collimator、energy window、matrix、zoom",
      "病人是否能穩定維持姿勢",
      "是否需要固定帶、枕頭、膝下墊、 head holder",
      "先看 raw data，不要只看重建結果",
      "是否有 motion、截切、金屬、污染、注射滲漏",
      "重建參數是否與科內 preset 一致",
      "report 中是否完整記錄 tracer、activity、注射時間、掃描時間與特殊事件"
    ],
    "pitfalls": [
      "忽略病人準備環境",
      "只看重建，不看 raw data",
      "忘記某些檢查是「動態或多時間點」才有判讀價值",
      "用錯 collimator，特別是 I-123 類檢查"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ],
    "note": "此頁以肺灌流 / VQ 總覽章節整理，重點放在灌流與配準品質。"
  },
  "Meckel": {
    "title": "Meckel's diverticulum scan",
    "source": "Gastrointestinal Bleeding Scintigraphy",
    "acquisition": [
      [
        "Tracer",
        "Tc-99m labeled RBC"
      ],
      [
        "Acquisition",
        "注射後立即 dynamic；先密集 frame，必要時延長至較晚時間點"
      ],
      [
        "Matrix",
        "常用 128 x 128"
      ],
      [
        "View",
        "anterior abdomen / pelvis 為主"
      ]
    ],
    "processing": [
      "真正陽性要符合：先出現、強度增加、沿腸道移動",
      "自由鎝、泌尿系統、子宮、血管、脾臟都可能造成誤判"
    ],
    "qc": [
      "臨床問題是否清楚",
      "選的 tracer 是否真的回答該問題",
      "病人準備是否完成",
      "是否有近期造影劑、藥物、食物或手術影響判讀",
      "是否需排尿、補水、停藥、 thyroid blockade、 premedication",
      "注射是否順利，是否疑似 extravasation",
      "detector / camera / CT 是否通過當日 QC",
      "是否選對 collimator、energy window、matrix、zoom",
      "病人是否能穩定維持姿勢",
      "是否需要固定帶、枕頭、膝下墊、 head holder",
      "先看 raw data，不要只看重建結果",
      "是否有 motion、截切、金屬、污染、注射滲漏",
      "重建參數是否與科內 preset 一致",
      "report 中是否完整記錄 tracer、activity、注射時間、掃描時間與特殊事件"
    ],
    "pitfalls": [
      "未取得或未對照近期內視鏡、CT / MRI 解剖影像",
      "忽略用藥、禁食時長或近期介入對 GI 動態檢查的影響",
      "只看單張靜態影像下結論，未回看動態 raw sequence",
      "少拍關鍵延遲時間點，無法區分間歇性與持續性異常"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ],
    "note": "Meckel 以 GI 類腹部動態收像原則為基礎，Tc-99m pertechnetate 注射後 1 frame/min × 30–60 min，前處理（禁食、H2 blocker）為敏感度關鍵。"
  },
  "Cystography": {
    "title": "Radionuclide cystography",
    "source": "",
    "acquisition": [
      "常用在 thyroid、DMSA、bone whole-body、GI bleed、lung perfusion",
      "關鍵是：",
      "collimator 選對",
      "counts 足夠",
      "病人位置穩",
      "視野完整"
    ],
    "processing": [
      "filling、voiding、post-void 都要完整記錄",
      "time stamping 很重要",
      "污染與尿管位置問題常是判讀陷阱"
    ],
    "qc": [
      "臨床問題是否清楚",
      "選的 tracer 是否真的回答該問題",
      "病人準備是否完成",
      "是否有近期造影劑、藥物、食物或手術影響判讀",
      "是否需排尿、補水、停藥、 thyroid blockade、 premedication",
      "注射是否順利，是否疑似 extravasation",
      "detector / camera / CT 是否通過當日 QC",
      "是否選對 collimator、energy window、matrix、zoom",
      "病人是否能穩定維持姿勢",
      "是否需要固定帶、枕頭、膝下墊、 head holder",
      "先看 raw data，不要只看重建結果",
      "是否有 motion、截切、金屬、污染、注射滲漏",
      "重建參數是否與科內 preset 一致",
      "report 中是否完整記錄 tracer、activity、注射時間、掃描時間與特殊事件"
    ],
    "pitfalls": [
      "注射不是 bolus 或有 extravasation，會直接扭曲 renogram。",
      "hydration 不足、未排尿或 bladder outlet problem 會讓排空假性變差。",
      "只看 T1/2、Tmax，不回看 raw cine 與 ROI 放置。"
    ],
    "localFixedFields": [
      "示蹤劑與實際活度",
      "注射時間、開始收像時間與時間差",
      "固定的 reconstruction preset 名稱與版本",
      "視野 / 體位 / 幾何條件",
      "是否加做 SPECT/CT、診斷 CT 或延遲補拍"
    ],
    "note": "本站目前使用腎泌尿總覽章節整理；若未來另建兒科專卷，再替換成專檔版。"
  },
  "MUGA": {
    "title": "MUGA",
    "source": "以心臟核醫總覽與共通技術模板整理。",
    "acquisition": [
      "ECG gating 必須穩定，先確認心律與 R-wave 偵測品質。",
      "多角度 planar 收像前，先讓左心室與左心房分離良好。",
      "收像時間與 counts 目標要固定，方便前後 EF 追蹤可比。"
    ],
    "processing": [
      "ROI 畫法、background ROI 與 edge detection 規則要固定。",
      "同一病人追蹤時，gating 設定與計算軟體版本不要任意切換。",
      "若節律不整明顯，EF 數值要和原始 gated sequence 一起判讀。"
    ],
    "qc": [
      "energy peaking 與 uniformity 每日 QC",
      "ECG gating 是否穩定",
      "motion review：尤其 stress 後病人較不穩",
      "AC CT 是否對位",
      "reconstruction preset 是否一致"
    ],
    "pitfalls": [
      "軟組織衰減假性缺損",
      "心律不整造成 gating 失敗",
      "subdiaphragmatic activity 干擾下壁",
      "壓力流程條件未固定，會讓前後檢查不可比。",
      "只看 AC 或只看 gated function，沒回到 raw data。"
    ],
    "localFixedFields": [
      "RBC 標記方法與 labeling QC",
      "gating frame 數與 arrhythmia 接受規則",
      "LAO / best septal separation 幾何條件",
      "EF 計算軟體與版本"
    ],
    "note": "本條目提供共通 gated 心臟核醫收像、後處理與 QC 原則，用於心室功能評估與 EF 追蹤。"
  },
  "Venography": {
    "title": "Radionuclide venography",
    "source": "以共通 acquisition checklist 與動態平面成像模板整理。",
    "acquisition": [
      "注射一定要順利且對側比較條件一致，extravasation 會直接破壞判讀。",
      "dynamic frame timing 要固定，保留完整 early flow sequence。",
      "視野需涵蓋臨床問題區段，避免只留下局部靜態影像。"
    ],
    "processing": [
      "先看 raw dynamic cine，再談局部滯留或側支路徑。",
      "若有左右側比較，ROI 與顯示尺度要一致。",
      "靜態補拍只能補位置，不能取代早期流動資訊。"
    ],
    "qc": [
      "臨床問題是否清楚",
      "選的 tracer 是否真的回答該問題",
      "病人準備是否完成",
      "是否有近期造影劑、藥物、食物或手術影響判讀",
      "是否需排尿、補水、停藥、 thyroid blockade、 premedication",
      "注射是否順利，是否疑似 extravasation",
      "detector / camera / CT 是否通過當日 QC",
      "是否選對 collimator、energy window、matrix、zoom",
      "病人是否能穩定維持姿勢",
      "是否需要固定帶、枕頭、膝下墊、 head holder",
      "先看 raw data，不要只看重建結果",
      "是否有 motion、截切、金屬、污染、注射滲漏",
      "重建參數是否與科內 preset 一致",
      "report 中是否完整記錄 tracer、activity、注射時間、掃描時間與特殊事件"
    ],
    "pitfalls": [
      "是否有 TOF",
      "是否有 PSF",
      "是否有 penalized likelihood",
      "CT AC 是否成功",
      "是否有 metal artifact / respiratory misregistration"
    ],
    "localFixedFields": [
      "注射側與注射品質記錄",
      "dynamic frame timing",
      "視野起訖範圍",
      "是否加做延遲或局部補拍"
    ],
    "note": "本條目提供動態平面血流序列的共通收像與判讀原則，用於放射性核種靜脈攝影。"
  },
  "Lymphedema": {
    "title": "Lymphedema / lymphoscintigraphy",
    "source": "整理自 ISL 2023 consensus、SNMMI Appropriate Use Criteria 2023、下肢淋巴水腫 lymphoscintigraphy 研究與鄭醫師教學網站分級圖例。",
    "acquisition": [
      "遠端指(趾)間皮內或淺皮下注射最常見，注射層次、左右劑量與活動條件需固定。",
      "先做早期動態或早期靜態，再於 1–3 小時補延遲影像；必要時加做到更晚時點以區分單純延遲與真正阻塞。",
      "雙側比較時，姿勢、視野、顯示尺度與是否安排步行/按摩等刺激條件都應一致。"
    ],
    "processing": [
      "保留早期路徑與延遲節點影像，不要只留最後一張延遲相。",
      "描述時要把淋巴管上行、節點顯影時間、dermal backflow、部分阻塞與完全阻塞分開寫。",
      "若使用 transit time 或半定量指標，ROI、時間點與刺激條件必須完全一致。"
    ],
    "qc": [
      "臨床問題是否清楚",
      "選的 tracer 是否真的回答該問題",
      "病人準備是否完成",
      "是否有近期造影劑、藥物、食物或手術影響判讀",
      "是否需排尿、補水、停藥、 thyroid blockade、 premedication",
      "注射是否順利，是否疑似 extravasation",
      "detector / camera / CT 是否通過當日 QC",
      "是否選對 collimator、energy window、matrix、zoom",
      "病人是否能穩定維持姿勢",
      "是否需要固定帶、枕頭、膝下墊、 head holder",
      "先看 raw data，不要只看重建結果",
      "是否有 motion、截切、金屬、污染、注射滲漏",
      "重建參數是否與科內 preset 一致",
      "report 中是否完整記錄 tracer、activity、注射時間、掃描時間與特殊事件"
    ],
    "pitfalls": [
      "是否有 TOF",
      "是否有 PSF",
      "是否有 penalized likelihood",
      "CT AC 是否成功",
      "是否有 metal artifact / respiratory misregistration"
    ],
    "localFixedFields": [
      "注射部位與注射層次",
      "活動 / 按摩 / 步行規則",
      "早期與延遲固定時間點",
      "雙側顯示尺度與判讀用語"
    ],
    "note": "淋巴水腫攝影的核心在比較早期上行、延遲節點到達與 dermal backflow；若注射層次與刺激條件不固定，前後檢查很難比較。"
  },
  "SLN": {
    "title": "Sentinel lymph node mapping",
    "source": "整理自 EANM/SNMMI breast cancer guideline、EANM melanoma guideline、SNMMI Appropriate Use Criteria 2023 與 sentinel node radiology review。",
    "acquisition": [
      "依癌種選擇 peritumoral、subareolar、intradermal 或 scar-adjacent 注射法，並讓活度與手術時間匹配。",
      "保留早期動態與靜態定位，因為最早出現的節點才最符合 sentinel node 定義。",
      "解剖複雜、深層或多站引流時，應及早考慮多角度或 SPECT/CT，避免注射點 shine-through。"
    ],
    "processing": [
      "先區分第一站與第二站節點，再進行皮膚標記與位置描述。",
      "若節點靠近注射點或位置深層，需調整窗位或加做斜位 / SPECT/CT。",
      "手術溝通稿應包含節點數、最早顯影節點、異位引流與是否疑似第二站節點。"
    ],
    "qc": [
      "臨床問題是否清楚",
      "選的 tracer 是否真的回答該問題",
      "病人準備是否完成",
      "是否有近期造影劑、藥物、食物或手術影響判讀",
      "是否需排尿、補水、停藥、 thyroid blockade、 premedication",
      "注射是否順利，是否疑似 extravasation",
      "detector / camera / CT 是否通過當日 QC",
      "是否選對 collimator、energy window、matrix、zoom",
      "病人是否能穩定維持姿勢",
      "是否需要固定帶、枕頭、膝下墊、 head holder",
      "先看 raw data，不要只看重建結果",
      "是否有 motion、截切、金屬、污染、注射滲漏",
      "重建參數是否與科內 preset 一致",
      "report 中是否完整記錄 tracer、activity、注射時間、掃描時間與特殊事件"
    ],
    "pitfalls": [
      "是否有 TOF",
      "是否有 PSF",
      "是否有 penalized likelihood",
      "CT AC 是否成功",
      "是否有 metal artifact / respiratory misregistration"
    ],
    "localFixedFields": [
      "癌種對應的注射方式與注射點位",
      "動態與靜態固定時間點",
      "皮膚標記與術前溝通流程",
      "SPECT/CT 加做條件"
    ],
    "note": "前哨淋巴結造影的關鍵不是單看熱點，而是找出最早引流的第一站節點並把它準確交給外科；注射法與手術時序必須綁在一起。"
  },
  "LiverHemangioma": {
    "title": "Liver hemangioma scintigraphy",
    "source": "以 GI / 肝膽共通影像原則與多時間點 blood-pool 邏輯整理。",
    "acquisition": [
      "標記紅血球流程與 labeling QC 要穩定。",
      "早期血流、blood pool 與延遲時間點都要完整保留。",
      "必要時加局部 SPECT/CT 釐清肝內位置與背景器官重疊。"
    ],
    "processing": [
      "先看早期血流，再看延遲逐漸填入的型態。",
      "顯示尺度要讓病灶與肝背景可比較，避免單看最亮靜態圖。",
      "若與其他肝臟病灶鑑別，需結合先前 CT / MRI 解剖位置。"
    ],
    "qc": [
      "臨床問題是否清楚",
      "選的 tracer 是否真的回答該問題",
      "病人準備是否完成",
      "是否有近期造影劑、藥物、食物或手術影響判讀",
      "是否需排尿、補水、停藥、 thyroid blockade、 premedication",
      "注射是否順利，是否疑似 extravasation",
      "detector / camera / CT 是否通過當日 QC",
      "是否選對 collimator、energy window、matrix、zoom",
      "病人是否能穩定維持姿勢",
      "是否需要固定帶、枕頭、膝下墊、 head holder",
      "先看 raw data，不要只看重建結果",
      "是否有 motion、截切、金屬、污染、注射滲漏",
      "重建參數是否與科內 preset 一致",
      "report 中是否完整記錄 tracer、activity、注射時間、掃描時間與特殊事件"
    ],
    "pitfalls": [
      "是否有 TOF",
      "是否有 PSF",
      "是否有 penalized likelihood",
      "CT AC 是否成功",
      "是否有 metal artifact / respiratory misregistration"
    ],
    "localFixedFields": [
      "RBC 標記方法",
      "多時間點時序",
      "是否加做 SPECT/CT",
      "延遲相最晚時間點"
    ],
    "note": "本條目提供血池型肝臟檢查的共通收像、延遲比對與 SPECT/CT 定位原則，用於肝血管瘤 RBC 掃描。"
  },
  "Scrotal": {
    "title": "Scrotal scintigraphy",
    "source": "以共通 acquisition checklist 與急症血流檢查邏輯整理。",
    "acquisition": [
      "early flow sequence 必須完整，不能只留延遲靜態圖。",
      "左右側顯示尺度、ROI 與擺位要一致，方便比較血流差異。",
      "必要時補延遲相，釐清中心冷缺損與周邊充血型態。"
    ],
    "processing": [
      "先看動態灌流，再看 blood-pool 與延遲變化。",
      "左右對照顯示要固定，避免因視窗差異造成假性不對稱。",
      "若急診現場已高度懷疑扭轉，影像時序與臨床溝通比花俏後處理更重要。"
    ],
    "qc": [
      "臨床問題是否清楚",
      "選的 tracer 是否真的回答該問題",
      "病人準備是否完成",
      "是否有近期造影劑、藥物、食物或手術影響判讀",
      "是否需排尿、補水、停藥、 thyroid blockade、 premedication",
      "注射是否順利，是否疑似 extravasation",
      "detector / camera / CT 是否通過當日 QC",
      "是否選對 collimator、energy window、matrix、zoom",
      "病人是否能穩定維持姿勢",
      "是否需要固定帶、枕頭、膝下墊、 head holder",
      "先看 raw data，不要只看重建結果",
      "是否有 motion、截切、金屬、污染、注射滲漏",
      "重建參數是否與科內 preset 一致",
      "report 中是否完整記錄 tracer、activity、注射時間、掃描時間與特殊事件"
    ],
    "pitfalls": [
      "是否有 TOF",
      "是否有 PSF",
      "是否有 penalized likelihood",
      "CT AC 是否成功",
      "是否有 metal artifact / respiratory misregistration"
    ],
    "localFixedFields": [
      "dynamic frame timing",
      "左右對照顯示尺度",
      "是否補延遲相",
      "急診時序與回報流程"
    ],
    "note": "本條目提供急症血流檢查的共通收像與判讀核對原則，用於急性陰囊疼痛鑑別掃描。"
  },
  "Cisternography": {
    "title": "Radionuclide cisternography",
    "source": "以多時間點功能檢查原則整理。",
    "acquisition": [
      "腰椎穿刺、注入時間與體位變化都要完整記錄。",
      "2 至 4 小時、24 小時、必要時 48 小時時間點不可任意省略。",
      "頭顱與脊柱視野需覆蓋臨床問題路徑，避免只留單區影像。"
    ],
    "processing": [
      "閱讀重點是流動路徑與停留位置，不是單看某一張亮點。",
      "多時間點顯示順序要固定，方便比較上行、逆流或外漏。",
      "若用於 leak 評估，延遲鼻耳區補拍與對位說明要完整。"
    ],
    "qc": [
      "臨床問題是否清楚",
      "選的 tracer 是否真的回答該問題",
      "病人準備是否完成",
      "是否有近期造影劑、藥物、食物或手術影響判讀",
      "是否需排尿、補水、停藥、 thyroid blockade、 premedication",
      "注射是否順利，是否疑似 extravasation",
      "detector / camera / CT 是否通過當日 QC",
      "是否選對 collimator、energy window、matrix、zoom",
      "病人是否能穩定維持姿勢",
      "是否需要固定帶、枕頭、膝下墊、 head holder",
      "先看 raw data，不要只看重建結果",
      "是否有 motion、截切、金屬、污染、注射滲漏",
      "重建參數是否與科內 preset 一致",
      "report 中是否完整記錄 tracer、activity、注射時間、掃描時間與特殊事件"
    ],
    "pitfalls": [
      "是否有 TOF",
      "是否有 PSF",
      "是否有 penalized likelihood",
      "CT AC 是否成功",
      "是否有 metal artifact / respiratory misregistration"
    ],
    "localFixedFields": [
      "注入時間與體位",
      "固定追蹤時間點",
      "補拍區域與條件",
      "與重症 / 神經團隊回報節點"
    ],
    "note": "本條目提供多時間點 CSF 流動檢查的共通收像與判讀原則，用於腦脊髓液池掃描。"
  },
  "Ga67": {
    "title": "Ga-67 scintigraphy",
    "source": "以神經 / 肺 / 感染共通陷阱與延遲全身成像邏輯整理。",
    "acquisition": [
      "固定延遲時間點，必要時 48 至 72 小時追蹤。",
      "全身與局部補拍都要記錄，避免只剩一組延遲靜態圖。",
      "腸道準備與病人配合度會明顯影響腹部判讀。"
    ],
    "processing": [
      "先看全身分布，再回到局部定位與對位影像。",
      "若有多時間點，應比較訊號是否聚焦、變強或隨時間移動。",
      "與既有 CT、PET 或 WBC scan 的角色要分清楚，避免過度解讀。"
    ],
    "qc": [
      "臨床問題是否清楚",
      "選的 tracer 是否真的回答該問題",
      "病人準備是否完成",
      "是否有近期造影劑、藥物、食物或手術影響判讀",
      "是否需排尿、補水、停藥、 thyroid blockade、 premedication",
      "注射是否順利，是否疑似 extravasation",
      "detector / camera / CT 是否通過當日 QC",
      "是否選對 collimator、energy window、matrix、zoom",
      "病人是否能穩定維持姿勢",
      "是否需要固定帶、枕頭、膝下墊、 head holder",
      "先看 raw data，不要只看重建結果",
      "是否有 motion、截切、金屬、污染、注射滲漏",
      "重建參數是否與科內 preset 一致",
      "report 中是否完整記錄 tracer、activity、注射時間、掃描時間與特殊事件"
    ],
    "pitfalls": [
      "忽略病人準備環境",
      "只看重建，不看 raw data",
      "忘記某些檢查是「動態或多時間點」才有判讀價值",
      "用錯 collimator，特別是 I-123 類檢查"
    ],
    "localFixedFields": [
      "延遲時間點",
      "腸道準備規則",
      "全身與局部補拍條件",
      "對照影像需求"
    ],
    "note": "本條目提供延遲全身掃描與感染/發炎定位檢查的共通收像與 QC 原則，用於 Ga-67 發炎掃描。"
  },
  "NP59": {
    "title": "NP-59 adrenal cortical imaging",
    "source": "整理自 Endocrine Society 2025 PA 指南、J Nucl Med 2009 台灣 NP-59 SPECT/CT 研究與近年 adrenal imaging 文獻。",
    "acquisition": [
      "檢前先核對臨床問題、生化資料、CT/MRI 與可能干擾藥物，確認真的是要回答皮質功能問題。",
      "I-131 藥物需完成甲狀腺阻斷；原發性醛固酮增多症等情境常再依院內流程加入 dexamethasone suppression。",
      "常見為 Day 3、Day 5、Day 7 多時間點 planar，必要時加做 SPECT/CT；多時點幾何與縮放要固定。"
    ],
    "processing": [
      "先看整體背景是否可判讀，再比較雙側腎上腺是否有單側優勢、雙側增強或病灶側缺攝取。",
      "SPECT/CT 的價值在把功能熱點對回解剖位置，不宜只憑平面影像下手術側化結論。",
      "報告結論以支持哪一種功能模式為主，並註明判讀信心與技術限制。"
    ],
    "qc": [
      "臨床問題是否清楚",
      "選的 tracer 是否真的回答該問題",
      "病人準備是否完成",
      "是否有近期造影劑、藥物、食物或手術影響判讀",
      "是否需排尿、補水、停藥、 thyroid blockade、 premedication",
      "注射是否順利，是否疑似 extravasation",
      "detector / camera / CT 是否通過當日 QC",
      "是否選對 collimator、energy window、matrix、zoom",
      "病人是否能穩定維持姿勢",
      "是否需要固定帶、枕頭、膝下墊、 head holder",
      "先看 raw data，不要只看重建結果",
      "是否有 motion、截切、金屬、污染、注射滲漏",
      "重建參數是否與科內 preset 一致",
      "report 中是否完整記錄 tracer、activity、注射時間、掃描時間與特殊事件"
    ],
    "pitfalls": [
      "碘造影、含碘藥物、amiodarone、甲狀腺藥物干擾",
      "下巴遮擋、neck motion",
      "胃食道或口腔污染誤認為異常灶",
      "是否有 TOF",
      "是否有 PSF",
      "是否有 penalized likelihood"
    ],
    "localFixedFields": [
      "甲狀腺阻斷與 dexamethasone suppression 流程",
      "停藥 / 換藥規則",
      "Day 3 / 5 / 7 與 SPECT/CT 加做條件",
      "對照 CT / MRI 與手術前分型需求"
    ],
    "note": "NP-59 是腎上腺皮質功能定位檢查，重點在皮質自主分泌與左右側化，不是單看腫塊大小。"
  },
  "I131WBS": {
    "title": "I-131 whole-body survey",
    "source": "整理自 ATA 2015 differentiated thyroid cancer guideline、診斷性與治療後 I-131 WBS/SPECT-CT 相關綜述與近年實務更新。",
    "acquisition": [
      "檢前先核對是診斷性還是治療後 WBS，並記錄 TSH stimulation 方式、低碘飲食與近期含碘暴露。",
      "必須使用適合 I-131 的高能量 collimator 與對應 energy window；whole-body 掃描速度、局部 spot view 與延遲相條件要固定。",
      "掃描前排尿、更衣並檢查口鼻與皮膚污染；必要時針對可疑區域重拍，避免把唾液或尿液污染當成病灶。"
    ],
    "processing": [
      "先建立全身生理性分布地圖，再回到局部高攝取區辨認是甲狀腺床、淋巴結、遠端轉移還是表面污染。",
      "對平面影像不確定的焦點，應優先考慮 spot view 或 SPECT/CT 對位，而不是只靠窗位調整硬判讀。",
      "若為追蹤比較，掃描時點、儀器設定與是否加做 tomographic 補定位需盡量一致。"
    ],
    "qc": [
      "臨床問題是否清楚",
      "選的 tracer 是否真的回答該問題",
      "病人準備是否完成",
      "是否有近期造影劑、藥物、食物或手術影響判讀",
      "是否需排尿、補水、停藥、 thyroid blockade、 premedication",
      "注射是否順利，是否疑似 extravasation",
      "detector / camera / CT 是否通過當日 QC",
      "是否選對 collimator、energy window、matrix、zoom",
      "病人是否能穩定維持姿勢",
      "是否需要固定帶、枕頭、膝下墊、 head holder",
      "先看 raw data，不要只看重建結果",
      "是否有 motion、截切、金屬、污染、注射滲漏",
      "重建參數是否與科內 preset 一致",
      "report 中是否完整記錄 tracer、activity、注射時間、掃描時間與特殊事件"
    ],
    "pitfalls": [
      "碘造影、含碘藥物、amiodarone、甲狀腺藥物干擾",
      "下巴遮擋、neck motion",
      "胃食道或口腔污染誤認為異常灶",
      "是否有 TOF",
      "是否有 PSF",
      "是否有 penalized likelihood"
    ],
    "localFixedFields": [
      "TSH stimulation 與低碘飲食流程",
      "HE collimator 與 energy window",
      "全身掃描速度",
      "污染控制流程",
      "spot / SPECT/CT 加做條件"
    ],
    "note": "I-131 WBS 的判讀品質大量取決於 TSH stimulation、低碘飲食與污染控制；whole-body planar 只是起點，定位常需靠 spot view 或 SPECT/CT。"
  }
};

window.NMINFO_PROTOCOL_DATA = PROTOCOL_DATA;
